<?php


namespace console\daemons;


class WebSocketServer extends \consik\yii2websocket\WebSocketServer
{
    public $groups;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}